name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci --force
      - name: Get IP Publique
        run: wget -qO- icanhazip.com
      - name: Run Cypress Tests
        run: npx cypress run --spec "cypress/e2e/features/Consumer"
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        if: always()  # This ensures that the test report is always uploaded, even if the test step fails
        with:
          name: cypress-report
          path: |
            cypress/videos/**/*.mp4
            cucumber-report.html
            cypress/screenshots/**/*.png

