name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci --force
      - name: Run Cypress Tests
        run: npx cypress run --spec "cypress/e2e/features/Consumer"
